# Data Mapper Web Elements
profile_logo = "//img[@class='profile-logo']"
# data_mapper_svg_icon = "//div[@class='panel-toggles']//div[@class='panel-toggle data-mapper-panel__open']//div[@class='svg-icon w-embed']//*[local-name()='svg']//*[name()='path' and contains(@fill,'currentCol')]"
data_mapper_svg_icon = "//div[@class='point-mapper-toggles']//div[@class='panel-toggle data-mapper-panel__open']//div[@class='svg-icon w-embed']"
data_mapper_header = "//div[@class='point-data__header_title']//div[contains(text(),'Data Mapper')]"
demographic_menu = "//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Demographics')]"
age = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Age')]"
gender = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Gender')]"
race = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Race')]"
rob = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Region of Birth')]"
citizen = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Citizenship')]"
language = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Language')]"
youth_population = "//div[@class='truncate'][contains(text(),'Youth population')]"
youths = "//div[contains(text(),'Youths')]"
non_youths = "//div[contains(text(),'Non youth')]"
age_group = "//body[@class='body no-scroll']/div[@class='main']/div[@class='data-mapper']/" \
                "div[@class='data-mapper-content narrow-scroll']/div[@class='data-mapper-content__list']" \
                "/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]"
gender_subitem ="//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Gender')]"
race_subitem = "//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Race')]"
region_birth = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Region of Birth')]"
region_birth_subitem = "//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Region of Birth')]"
citizen_subitem = "//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Citizenship')]"
language_test_subitem = "//div[contains(text(),'Language test')]"
population ="//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Population')]"
education ="//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Education')]"
family_living_env ="//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Family & Living Environment')]"
poverty ="//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Poverty')]"
households ="//div[contains(text(),'Households')]"
water_services = "//div[contains(text(),'Water Services')]"
population_age_group = "//body[@class='body no-scroll']/div[@class='main']/div[@class='data-mapper']/div[@class='data-mapper-content narrow-scroll']/div[@class='data-mapper-content__list']/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]"
water_services_good = "//div[contains(text(),'Good')]"
water_services_poor = "//div[contains(text(),'Poor')]"
water_services_average ="//div[contains(text(),'Average')]"
water_services_no_access ="//div[contains(text(),'No access')]"
water_services_not_use = "//div[contains(text(),'Do not use')]"
water_services_unspecified="//div[2]//div[2]//div[1]//div[1]//div[2]//div[1]//div[1]//div[2]//div[1]//a[6]//div[2]"
race_other = "//div[@class='data-category']//div[3]//div[2]//div[1]//div[1]//div[2]//div[1]//a[1]//div[2]"
race_white = "//div[contains(text(),'White')]"
race_coloured = "//div[contains(text(),'Coloured')]"
race_black_african = "//div[contains(text(),'Black african')]"
race_indian_asian = "//div[contains(text(),'Indian or asian')]"
race_black_african_header = "//div[@class='filters__header_name']//div[contains(text(),'Race (Black african)')]"

