# Data Mapper Web Elements
class DataMapper:
    profile_logo = "//img[@class='profile-logo']"
    # data_mapper_svg_icon = "//div[@class='panel-toggles']//div[@class='panel-toggle data-mapper-panel__open']//div[@class='svg-icon w-embed']//*[local-name()='svg']//*[name()='path' and contains(@fill,'currentCol')]"
    data_mapper_svg_icon = "//div[@class='point-mapper-toggles']//div[@class='panel-toggle data-mapper-panel__open']//div[@class='svg-icon w-embed']"
    data_mapper_header = "//div[@class='point-data__header_title']//div[contains(text(),'Data Mapper')]"
    demographic_menu = "//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Demographics')]"
    age = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Age')]"
    gender = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Gender')]"
    race = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Race')]"
    rob = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Region of Birth')]"
    citizen = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Citizenship')]"
    language = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Language')]"
    youth_population = "//body[@class='body no-scroll']/div[@class='main']/div[@class='data-mapper']/div[@class='data-mapper-content narrow-scroll']/div[@class='data-mapper-content__list']/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]"
    youths = "//div[@class='data-mapper-content narrow-scroll']//div[1]//div[2]//div[1]//div[1]//div[2]//div[1]//div[2]//div[2]//div[1]//a[1]"
    non_youths = "//div[@class='data-mapper-content narrow-scroll']//div[1]//div[2]//div[1]//div[1]//div[2]//div[1]//div[2]//div[2]//div[1]//a[2]"
    age_group = "//body[@class='body no-scroll']/div[@class='main']/div[@class='data-mapper']/"\
                "div[@class='data-mapper-content narrow-scroll']/div[@class='data-mapper-content__list']"\
                "/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]"
    gender_subitem = "//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Gender')]"
    race_subitem = "//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Race')]"
    region_birth = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Region of Birth')]"
    region_birth_subitem = "//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Region of Birth')]"
    citizen_subitem = "//div[@class='data-category__h3_trigger']//div[@class='truncate'][contains(text(),'Citizenship')]"
    language_test_subitem = "//div[contains(text(),'Language test')]"
    population = "//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Population')]"
    education = "//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Education')]"
    family_living_env = "//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Family & Living Environment')]"
    poverty = "//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Poverty')]"
    households = "//div[contains(text(),'Households')]"
    water_services = "//div[contains(text(),'Water Services')]"
    population_age_group = "//body[@class='body no-scroll']/div[@class='main']/div[@class='data-mapper']/div[@class='data-mapper-content narrow-scroll']/div[@class='data-mapper-content__list']/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]"
    water_services_good = "//div[contains(text(),'Good')]"
    water_services_poor = "//div[contains(text(),'Poor')]"
    water_services_average = "//div[contains(text(),'Average')]"
    water_services_no_access = "//div[contains(text(),'No access')]"
    water_services_not_use = "//div[contains(text(),'Do not use')]"
    water_services_unspecified = "//div[2]//div[2]//div[1]//div[1]//div[2]//div[1]//div[1]//div[2]//div[1]//a[6]//div[2]"
    race_other = "//div[@class='data-category']//div[3]//div[2]//div[1]//div[1]//div[2]//div[1]//a[1]//div[2]"
    race_white = "//div[contains(text(),'White')]"
    race_coloured = "//div[contains(text(),'Coloured')]"
    race_black_african = "//div[contains(text(),'Black african')]"
    race_indian_asian = "//div[contains(text(),'Indian or asian')]"
    race_black_african_header = "//div[@class='filters__header_name']//div[contains(text(),'Race (Black african)')]"


class RichData:
    rich_data_icon = "//div[@class='point-mapper-toggles']//div[@class='panel-toggle rich-data-panel__open']//div[@class='svg-icon w-embed']"
    rich_data_navigation_summary = "//div[contains(text(),'Facilities in this Location')]"
    rich_data_navigation_demographic = "//div[@class='rich-data-nav__item-text']"\
                                       "//div[@class='truncate'][contains(text(),'Demographics')]"
    rich_data_demographics_header = "//h2[contains(text(),'Demographics')]"
    rich_data_age_header = "//h3[contains(text(),'Age')]"
    rich_data_gender_header = "//h3[contains(text(),'Gender')]"
    rich_data_race_header = "//h3[contains(text(),'Race')]"
    rich_data_rob_header = "//h3[contains(text(),'Region of Birth')]"
    rich_data_citizenship_header = "//h3[contains(text(),'Citizenship')]"
    rich_data_language_header = "//h3[contains(text(),'Language')]"
    rich_data_navigation_population = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Population')]"
    rich_data_population = "//h2[contains(text(),'Population')]"
    rich_data_household = "//h2[contains(text(),'Population')]"
    rich_data_navigation_education = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Education')]"
    rich_data_education = "//h2[contains(text(),'Education')]"
    rich_data_attendance = "//h3[contains(text(),'Attendance')]"
    rich_data_navigation_family = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Family & Living Environment')]"
    rich_data_family = "//h2[contains(text(),'Family & Living Environment')]"
    rich_data_housing = "//h3[contains(text(),'Housing')]"
    rich_data_health = "//h3[contains(text(),'Health')]"
    rich_data_navigation_poverty = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Poverty')]"
    rich_data_poverty_header = "//h2[contains(text(),'Poverty')]"
    rich_data_mpi_header = "//h3[contains(text(),'MPI')]"


class Map:
    map_search_location = "//input[@id='Location']"
    map_search_cape_town_text = "cape town"
    map_search_cape_town = "//body[@class='body no-scroll']/div[@class='main']/div[@class='nav']/div[@class='nav__content']/div[@id='w-node-926b3e9c8568-e148319d']/div[@class='nav__search_dropdown']/div[@class='search__dropdown_plate']/div[@class='search__dropdown_scroll narrow-scroll']/div[@class='search__dropdown_content']/div[@class='search__dropdown_list']/div[2]"
    map_search_cape_town_country = "//div[@class='truncate text-center'][contains(text(),'South Africa')]"
    map_search_cape_town_province = "//div[@class='truncate text-center'][contains(text(),'Western Cape')]"
    map_search_cape_town_municipality = "//div[@class='truncate text-center'][contains(text(),'City of Cape Town')]"
    map_zoom_in = "//a[@class='leaflet-control-zoom-in']"
    map_zoom_out = "//a[@class='leaflet-control-zoom-out']"
    map_search_result_first = "//div[@class='search__dropdown_content']//div[1]//div[1]//div[1]//div[1]"
    map_profile_highlight_age_percentage = "//div[contains(text(),'% 20 - 24 year olds')]"
    map_profile_highlight_female_population = "//div[contains(text(),'female population')]"
    map_profile_highlight_problem_communication = "//div[@class='location-highlight__title'][contains(text(),'Problems communicating')]"
    canvas = "//canvas[@class='leaflet-zoom-animated']"


# Tutorial Web Elements
class Tutorial:
    tutorial = "//div[contains(text(),'Tutorial')]"
    tutorial_header = "//span[@class='profile-name']"
    tutorial_introduction = "//span[contains(text(),'Introduction:')]"
    tutorial_location_search = "//span[contains(text(),'Location Search:')]"
    tutorial_location_panel = "//span[contains(text(),'Location Panel:')]"
    tutorial_rich_data = "//span[contains(text(),'Rich Data:')]"
    tutorial_point_mapper = "//span[contains(text(),'Point Mapper:')]"
    tutorial_data_mapper = "//span[contains(text(),'Data Mapper:')]"
    tutorial_learn_more = "//span[contains(text(),'Learn more:')]"
    tutorial_next_button = "//div[@class='text-block']"
    tutorial_back_button = "//div[@class='tutorial__slide_button previous']//div[@class='svg-icon w-embed']"
    tutorial_data_filtering = "//span[contains(text(),'Data Filtering:')]"
    tutorial_close_button = "//div[@class='tutorial__close']//div[@class='svg-icon w-embed']"
