map_search_location = "//input[@id='Location']"
map_search_cape_town_text = "cape town"
map_search_cape_town = "//div[@class='search__dropdown_list']//div[2]//div[1]//div[1]//div[1]"
map_search_cape_town_country = "//div[@class='truncate text-center'][contains(text(),'South Africa')]"
map_search_cape_town_province = "//div[@class='truncate text-center'][contains(text(),'Western Cape')]"
map_search_cape_town_municipality = "//div[@class='truncate text-center'][contains(text(),'City of Cape Town')]"
