rich_data_icon = "//div[@class='point-mapper-toggles']//div[@class='panel-toggle rich-data-panel__open']//div[@class='svg-icon w-embed']"
rich_data_navigation_summary = "//div[contains(text(),'Navigate to:')]"
rich_data_navigation_demographic = "//div[@class='rich-data-nav__item-text']" \
             "//div[@class='truncate'][contains(text(),'Demographics')]"
rich_data_demographics_header = "//h2[contains(text(),'Demographics')]"
rich_data_age_header = "//h3[contains(text(),'Age')]"
rich_data_gender_header = "//h3[contains(text(),'Gender')]"
rich_data_race_header = "//h3[contains(text(),'Race')]"
rich_data_rob_header = "//h3[contains(text(),'Region of Birth')]"
rich_data_citizenship_header = "//h3[contains(text(),'Citizenship')]"
rich_data_language_header = "//h3[contains(text(),'Language')]"
rich_data_navigation_population = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Population')]"
rich_data_population = "//h2[contains(text(),'Population')]"
rich_data_household = "//h2[contains(text(),'Population')]"
rich_data_navigation_education = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Education')]"
rich_data_education = "//h2[contains(text(),'Education')]"
rich_data_attendance = "//h3[contains(text(),'Attendance')]"
rich_data_navigation_family = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Family & Living Environment')]"
rich_data_family = "//h2[contains(text(),'Family & Living Environment')]"
rich_data_housing = "//h3[contains(text(),'Housing')]"
rich_data_health = "//h3[contains(text(),'Health')]"
rich_data_navigation_poverty = "//div[@class='rich-data-nav__item-text']//div[@class='truncate'][contains(text(),'Poverty')]"
rich_data_poverty_header = "//h2[contains(text(),'Poverty')]"
rich_data_mpi_header = "//h3[contains(text(),'MPI')]"