# Tutorial Web Elements
tutorial = "//div[contains(text(),'Tutorial')]"
tutorial_header = "//span[@class='profile-name']"
tutorial_introduction = "//span[contains(text(),'Introduction:')]"
tutorial_location_search = "//span[contains(text(),'Location Search:')]"
tutorial_location_panel = "//span[contains(text(),'Location Panel:')]"
tutorial_rich_data = "//span[contains(text(),'Rich Data:')]"
tutorial_point_mapper = "//span[contains(text(),'Point Mapper:')]"
tutorial_data_mapper = "//span[contains(text(),'Data Mapper:')]"
tutorial_learn_more = "//span[contains(text(),'Learn more:')]"
tutorial_next_button = "//div[@class='text-block']"
tutorial_back_button = "//div[@class='tutorial__slide_button previous']//div[@class='svg-icon w-embed']"
tutorial_data_filtering = "//span[contains(text(),'Data Filtering:')]"
tutorial_close_button = "//div[@class='tutorial__close']//div[@class='svg-icon w-embed']"
