name: "Unit & GUI tests"
on: [ push, pull_request ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install modules
        run: yarn
      - name: Build bundles
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Run gui tests
        run: yarn test:gui
